# Site settings
encoding: utf-8
title: Song Cafe #site title
name: The Song Cafe  #your name
description: Personalized, Affordable Songs #Your description
image: images/songcafecup.png #Url of your image of dimension 306x394px

baseurl: "/thesongcafe" # the subpath of your site, e.g. /blog/
url: "malinowski.studio/thesongcafe" # the base hostname & protocol for your site
twitter_username: kanishkkunal
github_username:  kanishkkunal
behance_username:
linkedin_url: "https://www.linkedin.com/in/kanishkkunal"
googleplus_url: "http://plus.google.com/+KanishkKunal"

#feeds url
feeds: http://feeds.feedburner.com/kanishkkunal

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: <!--Number-->

# disqus shortname
disqus: kanishk

# paging settings
paginate: 8

# Build settings
markdown: kramdown
permalink: /:title/

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :compressed

# Use the following plug-ins
gems:
#  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"


# Exclude these files from production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE
    - _config_dev.yml
